apiVersion: apps/v1
kind: Deployment
metadata:
  name: blobby-ui
  namespace: blobby-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blobby-ui
  template:
    metadata:
      labels:
        app: blobby-ui
    spec:
      containers:
      - name: blobby-ui
        image: ghcr.io/ricochet/blobby-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: blobby-ui
  namespace: blobby-ui
spec:
  type: NodePort
  selector:
    app: blobby-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blobby-ui
  namespace: blobby-ui
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: blobby.localhost.cosmonic.sh
    http:
      paths:
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: blobby-ui
            port:
              number: 80
