apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: Config
metadata:
  name: hono-swagger-ui-config
  namespace: {{ .Release.Namespace }}
spec:
  config:
    - name: host
      value: "{{ .Values.component.hostname }}"
