# For the 'http-trigger' helm chart
components:
  - name: blobstore
    image: ghcr.io/cosmonic-labs/components/http-blobstore:0.1.0

ingress:
  host: "blobstore.localhost.cosmonic.sh"

hostInterfaces:
  - namespace: wasi
    package: blobstore
    version: 0.2.0-draft
    interfaces:
      - blobstore
  - namespace: wasi
    package: config
    version: 0.2.0-draft
    interfaces:
      - runtime
