---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cosmonic-control-welcome-tour
  annotations:
    description: 'Cosmonic Control Welcome Tour'
spec:
  components:
    - name: welcome-http-server
      type: component
      properties:
        image: file://./dist/cosmonic_control_welcome_tour_s.wasm
        config:
          - name: custom-config
            properties:
              consoleurl: 'localhost:8000'
      traits:
        - type: spreadscaler
          properties:
            instances: 1

    - name: http-server-capability
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.23.2
      traits:
        - type: link
          properties:
            target:
              name: welcome-http-server
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 0.0.0.0:9000
