name = "cosmonic-control-welcome-tour"
language = "typescript"
type = "component"
version = "0.1.0"

[component]
wit_world = "router"
wasm_target = "wasm32-wasip2"

build_command = "npm run install-and-build"
build_artifact = "dist/cosmonic_control_welcome_tour.wasm"
destination = "dist/cosmonic_control_welcome_tour_s.wasm"

[dev]
manifest = "dev.yaml"