apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: Component
metadata:
  name: http-server
  namespace: default
spec:
  image: ghcr.io/cosmonic-labs/components/http-server:0.1.0
  concurrency: 100
  replicas: 1
  hostSelector:
    matchLabels:
      "hostgroup": "default"
  configFrom:
    - name: http-server-config
  exports:
    - wit:
        namespace: wasi
        package: http
        interfaces:
          - incoming-handler
      target:
        provider:
          name: http-default
          namespace: cosmonic-system
        configFrom:
          - name: http-server-config
 