apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: Component
metadata:
  name: hello-world
spec:
  image: component-hello-world
  concurrency: 100
  replicas: 1
  hostSelector:
    matchLabels:
      hostgroup: default
  exports:
    - wit:
        namespace: wasi
        package: http
        interfaces:
          - incoming-handler
      target:
        provider:
          name: http-server
          namespace: hono
        configFrom:
          - name: component-http-config
