configurations:
  - kustomizeconfig.yaml

resources:
  - component-hello-world.yaml
  - config-hello-world.yaml
  - provider-http-server.yaml
  - config-http-server.yaml

images:
  - name: provider-http-server
    newName: ghcr.io/wasmcloud/http-server
    newTag: 0.27.0
  - name: component-hello-world
    newName: ghcr.io/cosmonic-labs/components/hello-world-hono
    newTag: 0.1.0
