apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: Provider
metadata:
  name: http-server
spec:
  image: provider-http-server
  replicas: 1
  configFrom:
    - name: provider-http-server
  hostSelector:
    matchLabels:
      hostgroup: default
