apiVersion: runtime.wasmcloud.dev/v1alpha1 
kind: Component
metadata:
  name: blobstore-fileserver-nats
  namespace: default
spec:
  image: ghcr.io/cosmonic-labs/components/blobstore-fileserver:0.1.2
  concurrency: 100
  replicas: 1
  hostSelector:
    matchLabels:
      "hostgroup": "default"
  configFrom:
    - name: blobstore-http-config
  exports:
    - wit:
        namespace: wasi
        package: http
        interfaces:
          - incoming-handler
      target:
        provider:
          name: http-default
          namespace: cosmonic-system
        configFrom:
          - name: blobstore-http-config
  imports:
    - wit:
        namespace: wasi
        package: blobstore
        interfaces:
          - blobstore
          - container
      target:
        provider: 
          name: blobstore-nats-provider
          namespace: default
        configFrom:
          - name: blobstore-nats-config
---
apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: Config
metadata:
  name: blobstore-http-config
  namespace: default
spec:
  config:
    - name: host
      value: "localhost:9091"