apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: Component
metadata:
  name: {{ .Values.component.name }}
spec:
  image: ghcr.io/cosmonic-labs/components/http-server:0.1.0
  concurrency: {{ .Values.component.concurrency }}
  replicas: {{ .Values.component.replicas }}
  hostSelector:
    matchLabels:
      "hostgroup": {{ .Values.component.hostgroup }}
  exports:
    - wit:
        namespace: wasi
        package: http
        interfaces:
         - incoming-handler
      target:
        provider:
          name: {{ .Values.provider.name }}
          namespace: {{ .Values.namespace.name }}
