apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: Config
metadata:
  name: {{ .Values.configComponent.name }}
spec:
  config:
    - name: {{ .Values.configComponent.configName }}
      value: {{ .Values.configComponent.configValue }}
