apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: Provider
metadata:
  name: {{ .Values.provider.name }}
spec:
  image: ghcr.io/wasmcloud/http-server:0.27.0
  replicas: {{ .Values.provider.replicas }}
  hostSelector:
    matchLabels:
      "hostgroup": {{ .Values.provider.hostgroup }}
  configFrom:
    - name: {{ .Values.configProvider.name }}