name: CI Hello World Component

on:
  push:
    paths:
      - 'hello-world/**'
      - '.github/workflows/ci-hello-world.yml'
  pull_request:
    paths:
      - 'hello-world/**'
      - '.github/workflows/ci-hello-world.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up wash
        uses: cosmonic-labs/setup-wash@composite

      - name: Add wasm32-wasip2 target
        run: rustup target add wasm32-wasip2

      - name: Build hello-world component
        working-directory: hello-world
        run: wash build
