name: CI Welcome Tour Component

on:
  push:
    paths:
      - 'welcome-tour/**'
      - '.github/workflows/ci-welcome-tour.yml'
  pull_request:
    paths:
      - 'welcome-tour/**'
      - '.github/workflows/ci-welcome-tour.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up wash
        uses: cosmonic-labs/setup-wash@composite

      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0

      - name: Install npm dependencies
        working-directory: welcome-tour
        run: npm ci

      - name: Build welcome-tour component
        working-directory: welcome-tour
        run: npm run build

      - name: Test welcome-tour component
        working-directory: welcome-tour
        run: npm test || npm run test || echo 'No test script defined.'
