namespace: control-demo-http-ingress-nginx

resources:
  - base            # create the necessary cluster resources
  - hello-world     # set up the demo application
  - ingress-nginx   # create the nginx ingress controller

patches:
  - # This patch will correct the domain name on the ingress resource.
    # You should replace `example.com` with your actual domain name and ensure
    # that the domain is properly configured to point to your cluster.
    target:
      kind: Ingress
      name: hello-world-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: example.com
